title: <strong>Alexandre B A Villares</strong>

site_name: Alexandre B A Villares

# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Alexandre B A Villares

# Short description (goes below the title; it will also be used in the RSS feed)
# description: Alexandre B A Villares

# Your name, as you want it to appear underneath each post and in the footer
author: Alexandre B A Villares

# Your email if you want it to be linked on the contact page
# author_email: 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
# url: 

# logo: /assets/logo.png

# google_analytics:

twitter_username: villares
github_username: villares